#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 42aa86dc-be9d-4663-953a-a5152ad4da88
# Source File: RegExTester.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
tgwAAB+LCAAAAAAABABlV8cK9EiSvhfUOzRzFYy8g38aSlKp5L0p6SbvvdfTb03vZWHzlKSBjMj4
TPyxsmTYs/niojX66zdZqqH/z7/Qf8P/+vv5+OuvP/pcFVUftXzVZlrUZX9bWfE+nWxZs/nf45L/
Af/fiX/u8cPc/Z12vQxHVqZw7uvF6hz7+t/BvDjPb1uHaAYzn3MZhDi86l1C9O3ZnVbWV91WYRUi
qcbXq+Ml8dWWQO6jEvCyng/p/WIrnnSjT9aF6EjsG77zHZB9YGQlnBFtz+xEVJitlO4eviHphQ0+
1zFGIVOg+HsFqm1Ed9y5ixj/fPAeKkTjvH6kEO/Ak2sicO64e9sQLd5uH178bQazLVA7Eqr90Opg
f+27ONP6MgvDZbGwVXUn9U3ZY/d8TIWx+EmOXO1AqgQ8ISJN8/6K1AKpWAM0I46UIsBAeiTJRIpU
+ZChpV2qeH6/+KPfIWtun83rrpw2eD68uNKh/NBy3klHcBzW2J6360ZWPulHJySX1UdJeSEFlgYS
qqP1Xsmh94UGy3W+8VGu1uT0SgeJpo/xfKy+Z0yxMPtd6Mf+SK7mqF3gefBh1HG8DodoZkuy28i2
6oVqD/KsE14bt8fMkqt9K4KT0bS/gKK8+/3CGKAGnnyrFB7evSkcAFe8wL56GejZALlSIUzohzEA
K44brFwaVYQNYwhKNMoHlpmBQPZlBplQ/i4G+3zU4LBKGlENAB+DTODH6G4mHAFabs79d69VLr20
QMiHKyp3P9wkLYOHZKyC7j11bpbsCftQfL0tA9DnY5DLyExU7mrkft7mI64LW85ynVASLHP0/C4P
E3iL0vdajJnczeDV36x7Z+4ospFj9H1y7m4mQeDn/jwfgS16QiHIzOoWuH8eYcl6fJsKO/LL1QGf
+PKlq/zyJUHOvA1grtIxY5TPAFFEhQOiJgfx3r1roreyPh96Gpur7yqaK5SDkyzD7o1XiiUFNeJ6
1e3BZ/9V7scNoGSsl1Ng8tNzrPjNaJq3T2KpDJz+wmOjsGj9+VB3FmZsAe55vfAU6fI1oG4TCjs9
kZCCE3p5aR6F1TH3GQuqccgRR2/LjcQhZDnFPlMudoDNTNLUh/l8VKuGvDQ88NySKKrLg2pOrjBA
+ex8Zlafutfrly1yzMfKP7VlNCvR+eH9kYVaywwDjooAVZuPljFhQTwfzeaQddx/C3BL0GCtHaSU
m4Jwg/vmVg42TZ+zmwsbHZxa9tt706JI3fZkDoIW+iLtMDbko904CSX5e9tOVFbCxeYiMSGhy4O0
qxMr0+EUrECeHMwNf2eg6W+fPBnKyFQ3AZrBH1xQumWlFNS3Y6k+RXFvNng/HznAnKgU+HqgHG6n
JId3ct5eyNTXjE4pQPQOBgKo0+xYiTzVqvbGWrCaqnKoNhvZx5jlaIUDLhB6P36MVLw87zBHH/YL
RI4ySB9JP6BAONpvCIjQVyg4fZRILh8rK9XTsko5ilzvlhlvPFwEXw9TNXgd3vfZPh8bCL3v97Ij
qjiomVyGm6uoOuS5Fk7gHQGeHi041kIAdsdT4x23qf+NWCaYeHcRjo2lFnpnXjA0hvAvUssYh0T7
2laxSHMWjBVytjvyVSbgO7b0kOCDCzEdd1GD6G3dCmAjQVt5VCKvvtvQpqTN14GXq7hNxPB8YMIx
EiYSE44A9G3VXsfCW/IYXT7YlCMeS8DRhw46dLkVAZY2io5P3wefdlNCBaLlpym8r7EwhAgk/SIV
hCn8r0hkP5GwrhXTPxD3w+s9iOqtLcNMZWRAJnrpdWv1ea88ZlTeR3blyZKdsg/qVsu6owXhnPlx
SMi2sHKos9HlFLWPZ84N1TIOS9oxfjem0PD95EHF5NmyM7PWkfubY7vVHT+AFIE9UTNp8GI6tSnt
LX0+rpjpGIKKSr2d1QLxnC1maHpZkvyaDm/HyC80SFSd4JbDWn477Dz3LheesqmQ2lAQwe+Jj94N
JKzRr0IwWUOpIJZWP5IpyY5wkacFwzYw2IiltBF3c6wAoudM0svC4YN0bZsqChF+k1KM3bv48l5I
mzNODbb9fBy1XTQXLrLkffp0ZAY4X4DcxyC5fJ9ZAzM5DC5HNyPst471i6ACjjKLZoERXcOfYOCk
h1ao045R8PJ8EI55LfxpHkJ4vfKNu3/1ZwPWNeSLmsoRdQmZ9lKotHzhU1TQ8JHgBmTu9WZNELl/
bx6GYrVlR7sDsR/qu5AjKxxEvr34KQMxWwD4ixUTA9ZroegfEmRiW7l4Y/hSQr4Sxq0usRHTu8R+
AR9tb+dz1WRW/4T6h3qPokkHNHB8DbcYYXBcgShhpdHvTrxvYiMVMDEy0p+Q1aa3XYWDdXXVEe+2
ZSc4PI6QrW4VtCVfKEE/Hxzxpen7bUSNMefgxjsSCBVzOIk+3qzttQBaknrfjcr8xEq1tBxqKq+j
cNXDeDuraSISc+o6dIDvT/R8ALaqoj9ngFEkgXSoTMwpqxlloXnfr8gn5WVapGBp3MRdU7ouBbsT
MNd3H5efXzixoWZVbDGmBZqI/7BQymXuWQu/EJ4GxdixOuAx+SiPE7FdEYYEd6yYdzukpRLrJ2oW
J9oS473wgeuX5pwYf6YhipFZuQLa8xG/4L7a5gpT4YHSEMnaRiOYS9yJaxKYiF3rN8uU9gLQl6DD
DhEBPDTSym1jGyru+6XS3xUWBlLtrdXz4doXZYf8+aHL9/3lPtFMs81yy0JGIWD6bZRKbbJDyEB9
+ebv/tjvtbFlEuuxQJXwYw3aiOJZvnqP7/rHlqW5AwzPKcYEWsslaxDlqME4/VLDa6xNS7LEX3Ya
+dYkGVQLKPDwlYboE/FKoYr2oKpb5mC3bcbfn9bfsBBGQiBSvOLT2tpffRCHCfxzHzka63BiZWKU
7FqeFkQ2I9BNd+0ky992Nz4BMFYmvqHdz5fgkl/9kAUDxkUDcMqN87k727fSHOGdzfGC5mHprNHA
vTsNBLzYBK+1owu6O8uhk42xZnpVFxYEghfkTk7Mh34KWGoZAKnrHpY74SphWXK65divmGGTlS7Y
i41umqDKz1rAyc2UE6xd9zKUkc/8fBt+GcONfz6i3zRLkz8fotzsBITbDkAMYbvOc4DWJDQzwDbf
MKgmvoPW6otkEKLD60rpU17AazcFsEuu6Yb5gYv3JZHkZm/5/Wmkr4g8kPeK0BbHbRkhYHHd6Km+
nzb32rD2WIQaUMtdQJz9QABBSF7ZoIs5sxIDXkLSxmYVgKbn8PmhHjV7FtP0y0jNPFNCKPiZZo2+
xZ8W6zi5frN5F0GJbt9RSTneYRk7/uMOjAtP6VrZA/41Bf/5A/7TNPzTPryWJevitsqWv8Dfyh/w
//Ypf/8P4tS2m7YMAAA=#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2019 v5.6.165
     Generated on:       7/31/2019 10:05 AM
     Generated by:       Chance Factor
     Organization:       Sonic Corporate
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2019
#>


#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-RegExTester_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formRegExTester = New-Object 'System.Windows.Forms.Form'
	$labelRegexTester = New-Object 'System.Windows.Forms.Label'
	$buttonCopyPattern = New-Object 'System.Windows.Forms.Button'
	$buttonTestPattern = New-Object 'System.Windows.Forms.Button'
	$panel2 = New-Object 'System.Windows.Forms.Panel'
	$rtbResults = New-Object 'System.Windows.Forms.RichTextBox'
	$labelResults = New-Object 'System.Windows.Forms.Label'
	$panel1 = New-Object 'System.Windows.Forms.Panel'
	$rtbCriteria = New-Object 'System.Windows.Forms.RichTextBox'
	$labelTestCrieria = New-Object 'System.Windows.Forms.Label'
	$labelPattern = New-Object 'System.Windows.Forms.Label'
	$tbPattern = New-Object 'System.Windows.Forms.TextBox'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$formRegExTester_Load={
		$buttonCopyPattern.Enabled = $false
		$rtbResults.Enabled = $false
	}
	
	$rtbCriteria_TextChanged={
		#TODO: Place custom script here
		if ($tbPattern.Text.Trim() -ne "")
		{
			Update-ResultsBlock
		}
		
	}
	
	$tbPattern_TextChanged={
		if ($tbPattern.Text.Trim() -ne "")
		{
			$buttonCopyPattern.Enabled = $true
			Update-ResultsBlock
		}
	}
	
	function Update-ResultsBlock
	{
		$rtbResults.Text = ""
		$array = $rtbCriteria.Lines
		
		foreach ($line in $array)
		{
			if ($line -match $tbPattern.Text)
			{
				$rtbResults.Text += "$line`n"
			}
			
		}
	}
	
	$buttonTestPattern_Click={
		Update-ResultsBlock
	}
	
	$buttonCopyPattern_Click= {
		$tbPattern.SelectAll()
		$tbPattern.Copy()
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formRegExTester.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonCopyPattern.remove_Click($buttonCopyPattern_Click)
			$buttonTestPattern.remove_Click($buttonTestPattern_Click)
			$rtbCriteria.remove_TextChanged($rtbCriteria_TextChanged)
			$tbPattern.remove_TextChanged($tbPattern_TextChanged)
			$formRegExTester.remove_Load($formRegExTester_Load)
			$formRegExTester.remove_Load($Form_StateCorrection_Load)
			$formRegExTester.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formRegExTester.SuspendLayout()
	$panel2.SuspendLayout()
	$panel1.SuspendLayout()
	#
	# formRegExTester
	#
	$formRegExTester.Controls.Add($labelRegexTester)
	$formRegExTester.Controls.Add($buttonCopyPattern)
	$formRegExTester.Controls.Add($buttonTestPattern)
	$formRegExTester.Controls.Add($panel2)
	$formRegExTester.Controls.Add($panel1)
	$formRegExTester.AutoScaleDimensions = '8, 17'
	$formRegExTester.AutoScaleMode = 'Font'
	$formRegExTester.BackColor = '0, 0, 64'
	$formRegExTester.ClientSize = '1049, 598'
	$formRegExTester.ForeColor = 'ButtonFace'
	#region Binary Data
	$formRegExTester.Icon = [System.Convert]::FromBase64String('
AAABAAEAICAAAAAAIACoEAAAFgAAACgAAAAgAAAAQAAAAAEAIAAAAAAAACAAAAAAAAAAAAAAAAAA
AAAAAAD9/f3//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7/
/v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+
/v7//v7+//7+/v/+/v7//v7+//39/f/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+
/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+
//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//f39//7+/v/+/v7//v7+//7+/v/+/v7/
/v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+
/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/9/f3//v7+//7+
/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+
//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7/
/v7+//39/f/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+
/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+
/v/+/v7//v7+//7+/v/+/v7//f39//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+
//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7/
/v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/9/f3//v7+//7+/v/+/v7//v7+//7+/v/+
/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+
/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//39/f/+/v7//v7+
//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7/
/v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+
/v7//f39//7+/v/+/v7/9fn9//Ty8v/+/vv//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+
/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//3+/v/09fj/9fTz
//79/f/+/v7//v7+//7+/v/9/f3//v7+//L+/v8hXaf/ZisA//7+6v/+/v7//v7+//7+/v/+/v7/
/v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+
/v7/+v7+/zxys/87IQv/+PLW//7+/v/+/v7//v7+//39/f/+/v7/o8zw/wYBAP/DnGv//v7+//7+
/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+
//7+/v/+/v7//v7+//7+/v/+/v7/uOn+/wAIM//Ri0b//v75//7+/v/+/v7//f39//7+/v9Pd6X/
EAoD/+3Utf/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+
/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/4/v7/H1aJ/0EIAP/+787//v7+//7+
/v/9/f3/7/7+/xA2X/9YEgz//vfe//7+/v/V8P7/kpKf/+DArf/+/v7//v7+//7+/v/a6vf/kpKS
/8q3oP/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v9qnMP/
AAAF/923jP/+/v7//v7+//39/f+8/f7/AAAz/7pwE//+/v7//v7+//7+/v8BOGP/QQoG//3v1P/+
/v7//f7+/1B8qf8BAAD/w5tv//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+
/v/+/v7//v7+/6rL5v8ABw7/tINd//7+/v/+/v7//f39/2u06v8AAAv/8Kxg//7+/v/+/v7//v7+
/5a84v8CAQD/qH9M//7+/v+k2P7/AAwf/3A/A//+8ub//v7+//7+/v/+/v7//v7+//7+/v/+/v7/
/v7+//7+/v/+/v7//v7+//7+/v/+/v7/xeH5/wYMEv+DWS///v7+//7+/v/9/f3/G3W8/xsAAP/+
3Jf//v7+//7+/v/+/v7//v7+/yJ9uv8cAAf/0siO/xgma/83Dwj//v7D//7+/v/+/v7//v7+//7+
/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/b9P7/CxFP/21GF//+/v7//v7+
//P9/f8YVaH/LAAA//72s//+/v7//v7+//7+/v/+/v7/5/j8/xwzT/8WFAj/AAMG/76TXf/+/v7/
/v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+/+b+/v8O
E3D/TiIA//7+5P/+/v7/6f39/xdOm/8wAAD//v66//7+/v/+/v7//v7+//7+/v/6/f7/Q2uh/wAA
AP8cAAD/9deq//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+
//7+/v/+/v7/5v7+/w4TcP9KHQD//v7e//7+/v/p/f3/F06b/zAAAP/+/rr//v7+//7+/v/+/v7/
/v7+/8/0+P8AFTP/Kg0N/wAJCf+NXTz//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+
/v7//v7+//7+/v/+/v7//v7+//7+/v/m/v7/DhNw/0odAP/+/t7//v7+//H9/f8aZK3/JAAA//7q
pv/+/v7//v7+//7+/v/g9P7/Fjl2/zQUAP/q2q7/VoHI/xkKAP/pvn7//v7+//7+/v/+/v7//v7+
//7+/v+Wqcr/hHx0//7z6f/+/v7//v7+//7+/v/+/v7//v7+/+b+/v8OE3D/VSoA//7+8P/+/v7/
/f39/1Sg4/8WAAD//taQ//7+/v/+/v7//v7+/2eVvP8BAAD/rYFR//7+/v/+/v7/DUVz/zIDAf/4
58j//v7+//7+/v/m6Ov//f39/05wqf8zIBL//u7b/+vt9P/8/PD//v7+//7+/v/+/v7/1u/+/woQ
P/90TSH//v7+//7+/v/9/f3/ktX+/wAAFv/kn1H//v7+//7+/v/N/v7/BxJG/1QzBv/38dT//v7+
//7+/v+Vu97/AAAA/6uBUv/+/v7/n9H+/xseIv/DhmX/Z5/C/3YqHf+jutX/IyVK/72CKf/+/v7/
/v7+//7+/v/A3PT/BQsR/5hsRf/+/v7//v7+//39/f/U/v7/ABJC/59OEf/+/vX//v7+//7+/v/+
/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/q/v7/a4Kh/yQzQf8bJB3/HQYG/yck
F/9yX0r/+eHJ//7+/v/+/v7//v7+/5i/3P8ABQv/wpVr//7+/v/+/v7//f39//7+/v8xW4D/ShEL
//7y2f/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/v/v7/
ZpC2/wAAGP8AAAD/bU0r//7mz//+/v7//v7+//7+/v/+/v7/YJO+/wAABP/82bL//v7+//7+/v/9
/f3//v7+/3GdyP8NBwH/5Mml//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+
/v/+/v7/rt7+/w8bJ/9gNh7/TXR5/1ocFf9KYnj/EAgT/86TPf/+/v7//v7+/+/+/v8QP3b/hDIA
//7+7v/+/v7//v7+//39/f/+/v7/u9/+/wMHEv+zh1H//v7+//7+/v/+/v7//v7+//7+/v/+/v7/
/v7+//7+/v/+/v7//v7+//7+/v/+/v7/ipSk//39+/9Zhrr/UyQX//704v+mrc7/9/a7//7+/v/+
/v7/ndf1/wYCIP/rsGv//v7+//7+/v/+/v7//f39//7+/v/5/v7/RIjO/1ERAP/+/tb//v7+//7+
/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+/0xrpf8rHxH//uza
//7+/v/+/v7//v7+//b+/v81Vp3/STAY//v15v/+/v7//v7+//7+/v/9/f3//v7+//7+/v/+/v7/
/v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+
/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//39
/f/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+
//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7/
/v7+//7+/v/+/v7//f39//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+
/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+
/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/9/f3//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+
//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7/
/v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//39/f/9/f3//f39//39/f/9
/f3//f39//39/f/9/f3//f39//39/f/9/f3//f39//39/f/9/f3//f39//39/f/9/f3//f39//39
/f/9/f3//f39//39/f/9/f3//f39//39/f/9/f3//f39//39/f/9/f3//f39//39/f/9/f3/AAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA=')
	#endregion
	$formRegExTester.Name = 'formRegExTester'
	$formRegExTester.Text = 'RegEx Tester'
	$formRegExTester.add_Load($formRegExTester_Load)
	#
	# labelRegexTester
	#
	$labelRegexTester.AutoSize = $True
	$labelRegexTester.Font = 'Microsoft Sans Serif, 13.8pt, style=Bold'
	$labelRegexTester.Location = '425, 9'
	$labelRegexTester.Margin = '4, 0, 4, 0'
	$labelRegexTester.Name = 'labelRegexTester'
	$labelRegexTester.Size = '155, 32'
	$labelRegexTester.TabIndex = 4
	$labelRegexTester.Text = 'Regex Tester'
	$labelRegexTester.UseCompatibleTextRendering = $True
	#
	# buttonCopyPattern
	#
	$buttonCopyPattern.Font = 'Microsoft Sans Serif, 10.2pt'
	$buttonCopyPattern.ForeColor = 'Black'
	$buttonCopyPattern.Location = '267, 549'
	$buttonCopyPattern.Margin = '4, 4, 4, 4'
	$buttonCopyPattern.Name = 'buttonCopyPattern'
	$buttonCopyPattern.Size = '174, 36'
	$buttonCopyPattern.TabIndex = 3
	$buttonCopyPattern.Text = 'Copy Pattern'
	$buttonCopyPattern.UseCompatibleTextRendering = $True
	$buttonCopyPattern.UseVisualStyleBackColor = $True
	$buttonCopyPattern.add_Click($buttonCopyPattern_Click)
	#
	# buttonTestPattern
	#
	$buttonTestPattern.Font = 'Microsoft Sans Serif, 10.2pt'
	$buttonTestPattern.ForeColor = 'Black'
	$buttonTestPattern.Location = '68, 549'
	$buttonTestPattern.Margin = '4, 4, 4, 4'
	$buttonTestPattern.Name = 'buttonTestPattern'
	$buttonTestPattern.Size = '172, 36'
	$buttonTestPattern.TabIndex = 2
	$buttonTestPattern.Text = 'Test Pattern'
	$buttonTestPattern.UseCompatibleTextRendering = $True
	$buttonTestPattern.UseVisualStyleBackColor = $True
	$buttonTestPattern.add_Click($buttonTestPattern_Click)
	#
	# panel2
	#
	$panel2.Controls.Add($rtbResults)
	$panel2.Controls.Add($labelResults)
	$panel2.Location = '515, 45'
	$panel2.Margin = '4, 4, 4, 4'
	$panel2.Name = 'panel2'
	$panel2.Size = '486, 500'
	$panel2.TabIndex = 1
	#
	# rtbResults
	#
	$rtbResults.Location = '4, 98'
	$rtbResults.Margin = '4, 4, 4, 4'
	$rtbResults.Name = 'rtbResults'
	$rtbResults.Size = '478, 398'
	$rtbResults.TabIndex = 3
	$rtbResults.Text = ''
	#
	# labelResults
	#
	$labelResults.AutoSize = $True
	$labelResults.Font = 'Microsoft Sans Serif, 16.2pt, style=Bold'
	$labelResults.Location = '181, 57'
	$labelResults.Margin = '4, 0, 4, 0'
	$labelResults.Name = 'labelResults'
	$labelResults.Size = '106, 37'
	$labelResults.TabIndex = 2
	$labelResults.Text = 'Results'
	$labelResults.UseCompatibleTextRendering = $True
	#
	# panel1
	#
	$panel1.Controls.Add($rtbCriteria)
	$panel1.Controls.Add($labelTestCrieria)
	$panel1.Controls.Add($labelPattern)
	$panel1.Controls.Add($tbPattern)
	$panel1.Location = '38, 45'
	$panel1.Margin = '4, 4, 4, 4'
	$panel1.Name = 'panel1'
	$panel1.Size = '456, 500'
	$panel1.TabIndex = 0
	#
	# rtbCriteria
	#
	$rtbCriteria.BackColor = 'Window'
	$rtbCriteria.Location = '4, 98'
	$rtbCriteria.Margin = '4, 4, 4, 4'
	$rtbCriteria.Name = 'rtbCriteria'
	$rtbCriteria.Size = '444, 398'
	$rtbCriteria.TabIndex = 3
	$rtbCriteria.Text = ''
	$rtbCriteria.add_TextChanged($rtbCriteria_TextChanged)
	#
	# labelTestCrieria
	#
	$labelTestCrieria.AutoSize = $True
	$labelTestCrieria.Font = 'Microsoft Sans Serif, 10.8pt'
	$labelTestCrieria.Location = '171, 68'
	$labelTestCrieria.Margin = '4, 0, 4, 0'
	$labelTestCrieria.Name = 'labelTestCrieria'
	$labelTestCrieria.Size = '102, 26'
	$labelTestCrieria.TabIndex = 2
	$labelTestCrieria.Text = 'Test Crieria'
	$labelTestCrieria.UseCompatibleTextRendering = $True
	#
	# labelPattern
	#
	$labelPattern.AutoSize = $True
	$labelPattern.Font = 'Microsoft Sans Serif, 10.8pt'
	$labelPattern.Location = '185, 6'
	$labelPattern.Margin = '4, 0, 4, 0'
	$labelPattern.Name = 'labelPattern'
	$labelPattern.Size = '66, 26'
	$labelPattern.TabIndex = 1
	$labelPattern.Text = 'Pattern'
	$labelPattern.UseCompatibleTextRendering = $True
	#
	# tbPattern
	#
	$tbPattern.Font = 'Microsoft Sans Serif, 12pt'
	$tbPattern.Location = '4, 36'
	$tbPattern.Margin = '4, 4, 4, 4'
	$tbPattern.Name = 'tbPattern'
	$tbPattern.Size = '444, 30'
	$tbPattern.TabIndex = 0
	$tbPattern.add_TextChanged($tbPattern_TextChanged)
	$panel1.ResumeLayout()
	$panel2.ResumeLayout()
	$formRegExTester.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formRegExTester.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formRegExTester.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formRegExTester.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $formRegExTester.ShowDialog()

} #End Function

#Call the form
Show-RegExTester_psf | Out-Null
